### ISSUE TITLE
When using the reading mode, will have layout issue

### ISSUE THREAD

**Issue by vnana-git** [x-Ai/obsidian-nifty-links#3]
當閱讀模式時，影片連結上方會一個不能播放的影片
---

<img width="816" alt="2023-10-13 (1)" src="https://github.com/x-Ai/obsidian-nifty-links/assets/28506374/85768e30-c054-4053-a93f-244d037b8632">

⬆️ When page in reading mode｜當頁面在閱讀模式時

<img width="786" alt="2023-10-13 (2)" src="https://github.com/x-Ai/obsidian-nifty-links/assets/28506374/5df63118-2887-4793-9082-8b720ad47cc3">

⬆️ When clicking the link｜當點擊pop-up的影片時

**Comment by x-Ai** [comment]
目前的代码没有考虑到您遇的这个问题，我会做测试并修改代码。

**Comment by vnana-git** [comment]
謝謝～
很喜歡你做的UI，真的和Notion的Bookmarks一模一樣～
用起來很舒服～～

在Obs有另一類似的套件
https://github.com/dhamaniasad/obsidian-rich-links
有需要可以做參考

**Comment by vnana-git** [comment]
另外在preview mode時還有發現一個問題，不知道是否可直接在程式碼上作解決
若在rich link底下沒有隔行，下面的文字都會變成一團

### 1. 完全沒有隔行
<img width="808" alt="01-A" src="https://github.com/x-Ai/obsidian-nifty-links/assets/28506374/53151698-fd74-4707-bb68-94e5bab35515">

^ Preview Mode
<img width="743" alt="01-B" src="https://github.com/x-Ai/obsidian-nifty-links/assets/28506374/580ab4f9-cebc-4454-90fe-fcb7e37b2f78">

^ Editing Mode

### 2. 直接在rich link 下隔行

<img width="793" alt="02-A" src="https://github.com/x-Ai/obsidian-nifty-links/assets/28506374/85f81955-07ee-4b78-8e0f-013e824dc810">

^ Preview Mode
<img width="739" alt="02-B" src="https://github.com/x-Ai/obsidian-nifty-links/assets/28506374/df014a4f-ce6b-48bb-a071-316cde484b88">

^ Editing Mode

### 3. 在heading中間隔行

<img width="799" alt="03-A" src="https://github.com/x-Ai/obsidian-nifty-links/assets/28506374/6380ccc5-6bc4-4b6a-a211-85d9949eb395">

^ Preview Mode
<img width="740" alt="03-B" src="https://github.com/x-Ai/obsidian-nifty-links/assets/28506374/06d2dbdb-f6dc-4c0f-b8ae-40654041bd3c">

^ Editing Mode

**Comment by x-Ai** [comment]
已经测试修改，您遇到的问题现在都已经修复
