### ISSUE TITLE
Doesn’t work with medium.com

### ISSUE THREAD

**Issue by Glormond** [x-Ai/obsidian-nifty-links#4]
It seems like plugin doesn’t do anything when applying to some websites. For example, medium.com.

For example, this particular link won’t convert into the embedded card at all:
https://medium.com/wise-well/the-brain-science-behind-aging-and-forgetting-1954c5c094ab

**Comment by x-Ai** [comment]
Hi, your feedback has been fixed, just update it.

**Comment by Glormond** [comment]
Yes, everything works fine now! Thanks for a quick fix!
