### ISSUE TITLE
请问链接没有任何变化是什么原因啊？

### ISSUE THREAD

**Issue by piwillLee** [x-Ai/obsidian-nifty-links#5]
Mac 版本 1.7.4 ，重启应用也是没有变化

**Comment by x-Ai** [comment]
> Mac 版本 1.7.4 ，重启应用也是没有变化

您详细描述一下遇到的问题。

**Comment by piwillLee** [comment]
> > Mac 版本 1.7.4 ，重启应用也是没有变化
> 
> 您详细描述一下遇到的问题。
开启插件后，链接复制到文档里面，没有显示卡片，依旧是链接，是还需要设置什么内容吗

**Comment by x-Ai** [comment]
> > > Mac 版本 1.7.4 ，重启应用也是没有变化
> > 
> > 
> > 您详细描述一下遇到的问题。
> > 开启插件后，链接复制到文档里面，没有显示卡片，依旧是链接，是还需要设置什么内容吗

请在链接上点击鼠标右键，即可看到转换为Nifty Links的菜单
