### ISSUE TITLE
Doesn't seem to do anything

### ISSUE THREAD

**Issue by avaramis** [x-Ai/obsidian-nifty-links#6]
I have installed, and enabled the plugin and looked at the settings.
I then paste a link into my notes and nothing happens. I hit ctrl + e to see it outside of editing mode but it's just a link.
I select the text and hit ctrl + p then search among my options for nifty or link and nothing obvious comes up.
I type / and review my options in case I need to add a link with "something" and nothing.
I came here to look for documentation on how to use and only see a screenshot of what I want my links to look like.

How do I do that?

**Comment by x-Ai** [comment]
> I have installed, and enabled the plugin and looked at the settings.
> I then paste a link into my notes and nothing happens. I hit ctrl + e to see it outside of editing mode but it's just a link.
> I select the text and hit ctrl + p then search among my options for nifty or link and nothing obvious comes up.
> I type / and review my options in case I need to add a link with "something" and nothing.
> I came here to look for documentation on how to use and only see a screenshot of what I want my links to look like.
> 
> How do I do that?

Please right click on the link to see the menu for converting to Nifty Links
