### ISSUE TITLE
Doesn't seem to do anything

### ISSUE THREAD

**Issue by joshuakalejaiye** [x-Ai/obsidian-nifty-links#7]
I read through https://github.com/x-Ai/obsidian-nifty-links/issues/6

> Please right click on the link to see the menu for converting to Nifty Links

I typed a word, highlighted and right clicked it, clicked 'add external link' and pasted in my link.
When  I right click this link, I do not see any option to convert to nifty link. 
I am on Mac, Obsidian ver 1.7.7

**Comment by x-Ai** [comment]
https://github.com/user-attachments/assets/341e5194-c91e-447d-af9f-a6b15bcc9c0c

**Comment by joshuakalejaiye** [comment]
Ah thank you! This works for me. 
I think you should add that video to the readme, or I am almost certain this will happen again with someone else.
